/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.chriswk.isharelib

import com.chriswk.isharelib.importers.MovieImporter
import com.chriswk.isharelib.importers.PersonImporter
import com.chriswk.isharelib.importers.SeriesImporter
import mu.KotlinLogging

val logger = KotlinLogging.logger {}
fun main(args: Array<String>) {
    val people = PersonImporter()
    listOf(55751L, 56725L, 1223786L, 1100L).forEach {
        logger.info { "Fetch $it" }
        people.fetchObject(it)
    }
    val movies = MovieImporter()
    listOf(87101L, 167948L).forEach { movies.fetchObject(it) }
    val series = SeriesImporter()
    listOf(1399L, 456L).forEach { series.fetchObject(it) }
}
